//! Continuous host VT state and exact xterm.js reset-target replay.
//!
//! The adapter is the production form of the fixture proof in
//! `research/20260809-124553-fut-tty/vt-proof`. Keep the replay compatibility
//! helpers in step with that proof when the pinned parser is upgraded.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};

use libghostty_vt::{
    fmt::{Format, Formatter, FormatterOptions},
    screen::{CellWide, Screen, TrackedGridRef},
    selection::Selection,
    style::{Palette, PaletteIndex, RgbColor, Style, StyleColor, Underline},
    terminal::{ColorScheme, Mode, Point, PointCoordinate},
    Error, Terminal, TerminalOptions,
};
use shipctl_module_api::TerminalColorTheme;

use super::projection::{
    ProjectedPoint, ProjectedSpace, TerminalAnchor, TerminalAnchorId, TerminalHistoryWindow,
};
use super::retention::TerminalRetentionPolicy;

pub struct VtReplayEngine {
    terminal: Terminal<'static, 'static>,
    responses: Arc<Mutex<Vec<u8>>>,
    color_scheme: Arc<Mutex<ColorScheme>>,
    /// The cells clients asked the host to keep pointing at. The tracked
    /// references live here, beside the terminal that moves them, and never
    /// leave: a client holds the handle only.
    anchors: HashMap<TerminalAnchorId, TrackedGridRef>,
    /// Handles are never reused, so a client that releases an anchor and asks
    /// again cannot be answered with a different cell.
    minted_anchors: u64,
    /// Whether a page has ever held a line for this terminal.
    ///
    /// The retention budget alone does not answer this. Retention is
    /// page-granular, so a nonzero budget below the page floor at a given
    /// geometry retains no rows at all. Watching history become non-empty is
    /// the statement that holds for every budget and every geometry.
    ///
    /// It stays true once set: a small budget evicts history back to empty, and
    /// such a terminal still reports the eviction.
    history_ever_retained: bool,
}

impl VtReplayEngine {
    pub fn new(
        cols: u16,
        rows: u16,
        theme: &TerminalColorTheme,
        retention: TerminalRetentionPolicy,
    ) -> Result<Self, String> {
        validate_dimensions(cols, rows)?;
        let responses = Arc::new(Mutex::new(Vec::new()));
        let color_scheme = Arc::new(Mutex::new(theme_color_scheme(theme)));
        let mut terminal = Terminal::new(TerminalOptions {
            cols,
            rows,
            max_scrollback: retention.bytes(),
        })
        .map_err(|error| format!("Failed to initialize terminal VT state: {error}"))?;

        terminal
            .on_pty_write({
                let responses = Arc::clone(&responses);
                move |_terminal, data| {
                    responses
                        .lock()
                        .unwrap_or_else(|error| error.into_inner())
                        .extend_from_slice(data);
                }
            })
            .map_err(|error| format!("Failed to install terminal PTY responder: {error}"))?;
        terminal
            .on_color_scheme({
                let color_scheme = Arc::clone(&color_scheme);
                move |_terminal| {
                    Some(
                        *color_scheme
                            .lock()
                            .unwrap_or_else(|error| error.into_inner()),
                    )
                }
            })
            .map_err(|error| format!("Failed to install terminal color responder: {error}"))?;

        let mut engine = Self {
            terminal,
            responses,
            color_scheme,
            anchors: HashMap::new(),
            minted_anchors: 0,
            history_ever_retained: false,
        };
        engine.apply_theme(theme)?;
        Ok(engine)
    }

    /// Parse bytes before they are published and return exactly the responses
    /// generated by this parse step for ordered write-back to the PTY.
    pub fn feed(&mut self, bytes: &[u8]) -> Vec<u8> {
        self.discard_responses();
        self.terminal.vt_write(bytes);
        self.note_retained_history();
        self.take_responses()
    }

    /// The host's current state as owned Shipctl values.
    ///
    /// This reads the semantic API rather than the ANSI formatter, so it is the
    /// only answer to "what does the host believe" that does not go through a
    /// second parser. Reading advances nothing.
    pub fn project(&self) -> Result<super::projection::TerminalProjection, String> {
        super::projection::project(&self.terminal)
    }

    /// A window of retained history as the same rows the viewport reports.
    pub fn project_history(
        &self,
        start_row: u32,
        rows: u32,
    ) -> Result<TerminalHistoryWindow, String> {
        super::projection::project_history(&self.terminal, start_row, rows)
    }

    /// Pins one cell and returns the handle a client keeps instead of a row
    /// number.
    ///
    /// The host holds the pin for as long as the client asks it to. Each pin
    /// adds work to every terminal mutation, so they are created on request and
    /// released on request, never on the host's own initiative.
    ///
    /// A history row past the end of history is refused here. The parser counts
    /// history coordinates from the oldest retained row and reads on into the
    /// active area rather than stopping at the end of history, so a client
    /// asking for a history row would otherwise be given a live one.
    pub fn anchor(
        &mut self,
        space: ProjectedSpace,
        at: ProjectedPoint,
    ) -> Result<TerminalAnchor, String> {
        if space == ProjectedSpace::History {
            let history_rows = self.scrollback_rows()?;
            if at.row as usize >= history_rows {
                return Err(format!(
                    "Cannot anchor history row {}: history holds {history_rows} rows",
                    at.row
                ));
            }
        }
        let tracked = self
            .terminal
            .track_grid_ref(space.at(at))
            .map_err(vt_error("anchor a terminal cell"))?;
        self.minted_anchors += 1;
        let id = TerminalAnchorId(self.minted_anchors);
        let anchor = read_anchor(&self.terminal, id, &tracked, self.loss_reported()?)?;
        self.anchors.insert(id, tracked);
        Ok(anchor)
    }

    /// Where an anchor is now, or `None` when the host holds no such handle.
    pub fn resolve_anchor(&self, id: TerminalAnchorId) -> Result<Option<TerminalAnchor>, String> {
        let loss_reported = self.loss_reported()?;
        self.anchors
            .get(&id)
            .map(|tracked| read_anchor(&self.terminal, id, tracked, loss_reported))
            .transpose()
    }

    /// Whether this terminal can report the loss of an anchored line.
    ///
    /// Read on every anchor answer rather than cached alone, so a terminal that
    /// has just retained its first row corrects itself without waiting for the
    /// next parse step.
    fn loss_reported(&self) -> Result<bool, String> {
        Ok(self.history_ever_retained || self.scrollback_rows()? > 0)
    }

    fn note_retained_history(&mut self) {
        if !self.history_ever_retained {
            self.history_ever_retained = self.loss_reported().unwrap_or(false);
        }
    }

    /// Drops an anchor. Answers whether the host was holding it, so a client
    /// releasing twice learns the difference.
    pub fn release_anchor(&mut self, id: TerminalAnchorId) -> bool {
        self.anchors.remove(&id).is_some()
    }

    /// Anchors the host is holding for clients.
    pub fn anchor_count(&self) -> usize {
        self.anchors.len()
    }

    /// Rows currently held in history. The host is the retention authority, so
    /// this is the only truthful answer to "how much history is there".
    pub fn scrollback_rows(&self) -> Result<usize, String> {
        self.terminal
            .scrollback_rows()
            .map_err(vt_error("read terminal scrollback rows"))
    }

    pub fn resize(&mut self, cols: u16, rows: u16) -> Result<(), String> {
        validate_dimensions(cols, rows)?;
        self.terminal
            .resize(cols, rows, 0, 0)
            .map_err(|error| format!("Failed to resize terminal VT state: {error}"))
    }

    /// Apply query-visible defaults and return an unsolicited color-scheme
    /// report only when the process enabled DEC mode 2031.
    pub fn set_theme(&mut self, theme: &TerminalColorTheme) -> Result<Vec<u8>, String> {
        self.apply_theme(theme)?;
        if !self
            .terminal
            .mode(Mode::COLOR_SCHEME_REPORT)
            .map_err(|error| format!("Failed to inspect color-report mode: {error}"))?
        {
            return Ok(Vec::new());
        }

        let mut response = [0u8; 32];
        let length = theme_color_scheme(theme)
            .encode_report(&mut response)
            .map_err(|error| format!("Failed to encode color-scheme report: {error}"))?;
        Ok(response[..length].to_vec())
    }

    /// Produce a reset-target replay without losing the inactive primary
    /// buffer while the alternate screen is active.
    pub fn replay(&mut self) -> Result<Vec<u8>, String> {
        self.discard_responses();
        let replay = if self
            .terminal
            .active_screen()
            .map_err(vt_error("inspect active terminal screen"))?
            == Screen::Primary
        {
            format_active_screen(&self.terminal)?
        } else {
            let alternate = format_active_screen(&self.terminal)?;
            self.terminal.vt_write(b"\x1b[?1049l");
            let primary = format_active_screen(&self.terminal)?;
            self.terminal.reset();
            self.terminal.vt_write(&primary);
            self.terminal.vt_write(&alternate);

            let mut replay = primary;
            replay.extend_from_slice(&alternate);
            replay
        };
        // Formatting/rebuilding state must never leak synthetic query replies
        // into the child stream.
        self.discard_responses();
        Ok(replay)
    }

    fn apply_theme(&mut self, theme: &TerminalColorTheme) -> Result<(), String> {
        let foreground = parse_rgb(&theme.foreground, "foreground")?;
        let background = parse_rgb(&theme.background, "background")?;
        let mut palette = Palette::default();
        for (index, value) in theme.palette.iter().enumerate() {
            let index = u8::try_from(index)
                .map_err(|_| "Terminal color palette has more than 256 entries".to_string())?;
            palette.set(
                PaletteIndex(index),
                parse_rgb(value, &format!("palette index {index}"))?,
            );
        }
        self.terminal
            .set_default_fg_color(Some(foreground))
            .and_then(|terminal| terminal.set_default_bg_color(Some(background)))
            .and_then(|terminal| terminal.set_default_color_palette(Some(palette)))
            .map_err(|error| format!("Failed to apply terminal color theme: {error}"))?;
        *self
            .color_scheme
            .lock()
            .unwrap_or_else(|error| error.into_inner()) = theme_color_scheme(theme);
        Ok(())
    }

    fn take_responses(&self) -> Vec<u8> {
        std::mem::take(
            &mut *self
                .responses
                .lock()
                .unwrap_or_else(|error| error.into_inner()),
        )
    }

    fn discard_responses(&self) {
        self.responses
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .clear();
    }
}

/// Copies an anchor's position out of the tracked reference.
///
/// A cell is named differently in each space and is not named at all in some of
/// them, so every space is asked and the ones with no answer stay `None`.
///
/// The parser answers a history coordinate for cells that are not in history,
/// counting them from the oldest retained row as the screen space does. That
/// number would send a client to the wrong row, so it is kept only while it
/// names retained history, which is what `project_history` reads.
fn read_anchor(
    terminal: &Terminal<'_, '_>,
    id: TerminalAnchorId,
    tracked: &TrackedGridRef,
    loss_reported: bool,
) -> Result<TerminalAnchor, String> {
    let at = |space: ProjectedSpace| -> Result<Option<ProjectedPoint>, String> {
        Ok(tracked
            .point(space.space())
            .map_err(vt_error("read an anchor position"))?
            .map(|point| ProjectedPoint {
                column: point.x,
                row: point.y,
            }))
    };
    let history_rows = terminal
        .scrollback_rows()
        .map_err(vt_error("read terminal scrollback rows"))?;
    Ok(TerminalAnchor {
        id,
        retained: tracked.has_value(),
        loss_reported,
        history: at(ProjectedSpace::History)?.filter(|point| (point.row as usize) < history_rows),
        screen: at(ProjectedSpace::Screen)?,
        viewport: at(ProjectedSpace::Viewport)?,
        active: at(ProjectedSpace::Active)?,
    })
}

pub fn validate_dimensions(cols: u16, rows: u16) -> Result<(), String> {
    if cols == 0 || rows == 0 {
        return Err("Terminal dimensions must be non-zero".to_string());
    }
    usize::from(cols)
        .checked_mul(usize::from(rows))
        .ok_or_else(|| "Terminal dimensions overflow the host cell count".to_string())?;
    Ok(())
}

fn parse_rgb(value: &str, field: &str) -> Result<RgbColor, String> {
    let value = value.trim();
    if value.len() != 7 || !value.starts_with('#') {
        return Err(format!("Terminal {field} must use #RRGGBB"));
    }
    let parse = |range: std::ops::Range<usize>| {
        u8::from_str_radix(&value[range], 16)
            .map_err(|_| format!("Terminal {field} must use #RRGGBB"))
    };
    Ok(RgbColor {
        r: parse(1..3)?,
        g: parse(3..5)?,
        b: parse(5..7)?,
    })
}

fn theme_color_scheme(theme: &TerminalColorTheme) -> ColorScheme {
    let Ok(background) = parse_rgb(&theme.background, "background") else {
        return ColorScheme::Dark;
    };
    let luminance = 0.299 * f64::from(background.r)
        + 0.587 * f64::from(background.g)
        + 0.114 * f64::from(background.b);
    if luminance / 255.0 > 0.5 {
        ColorScheme::Light
    } else {
        ColorScheme::Dark
    }
}

fn vt_error(context: &'static str) -> impl FnOnce(Error) -> String {
    move |error| format!("Failed to {context}: {error}")
}

fn format_active_screen(terminal: &Terminal<'_, '_>) -> Result<Vec<u8>, String> {
    let cursor_x = terminal
        .cursor_x()
        .map_err(vt_error("read cursor column"))?;
    let cursor_y = terminal.cursor_y().map_err(vt_error("read cursor row"))?;
    let cursor_pending_wrap = terminal
        .is_cursor_pending_wrap()
        .map_err(vt_error("read cursor wrap state"))?;
    let options = FormatterOptions::new()
        .with_format(Format::Vt)
        .with_unwrap(true)
        .with_palette(true)
        .with_modes(true)
        .with_scrolling_region(true)
        .with_tabstops(true)
        .with_pwd(true)
        .with_keyboard(true)
        .with_cursor(true)
        .with_style(true)
        .with_hyperlink(true)
        .with_protection(true)
        .with_kitty_keyboard(true)
        .with_charsets(true);
    let mut formatter = Formatter::new(terminal, options)
        .map_err(vt_error("initialize terminal replay formatter"))?;
    let mut replay = formatter
        .format_alloc(None)
        .map_err(vt_error("format terminal replay"))?
        .as_ref()
        .to_vec();
    let active_hyperlink = last_osc8(&replay);
    append_hyperlink_cells(terminal, &mut replay)?;
    append_blank_wrap_continuations(terminal, &mut replay)?;
    append_cursor_cell(terminal, cursor_x, cursor_y, &mut replay)?;
    if !cursor_pending_wrap {
        replay.extend_from_slice(format!("\x1b[{};{}H", cursor_y + 1, cursor_x + 1).as_bytes());
    }
    if let Some(active_hyperlink) = active_hyperlink {
        replay.extend_from_slice(&active_hyperlink);
    }
    Ok(replay)
}

fn append_cursor_cell(
    terminal: &Terminal<'_, '_>,
    cursor_x: u16,
    cursor_y: u16,
    replay: &mut Vec<u8>,
) -> Result<(), String> {
    let cursor_ref = terminal
        .grid_ref(Point::Active(PointCoordinate {
            x: cursor_x,
            y: u32::from(cursor_y),
        }))
        .map_err(vt_error("read terminal cursor cell"))?;
    let start_x = if cursor_ref
        .cell()
        .and_then(|cell| cell.wide())
        .map_err(vt_error("read terminal cursor cell width"))?
        == CellWide::SpacerTail
    {
        cursor_x
            .checked_sub(1)
            .ok_or_else(|| "Wide cursor spacer has no lead cell".to_string())?
    } else {
        cursor_x
    };
    let start_ref = terminal
        .grid_ref(Point::Active(PointCoordinate {
            x: start_x,
            y: u32::from(cursor_y),
        }))
        .map_err(vt_error("read terminal cursor lead cell"))?;
    let selection = Selection::new(start_ref, cursor_ref, false);
    let options = FormatterOptions::new()
        .with_format(Format::Vt)
        .with_unwrap(false)
        .with_trim(false)
        .with_selection(&selection)
        .with_cursor(false)
        .with_style(true)
        .with_hyperlink(true)
        .with_protection(true)
        .with_kitty_keyboard(true)
        .with_charsets(true);
    let mut formatter = Formatter::new(terminal, options)
        .map_err(vt_error("initialize terminal cell formatter"))?;
    replay.extend_from_slice(format!("\x1b[{};{}H", cursor_y + 1, start_x + 1).as_bytes());
    replay.extend_from_slice(
        formatter
            .format_alloc(None)
            .map_err(vt_error("format terminal cursor cell"))?
            .as_ref(),
    );
    Ok(())
}

fn append_blank_wrap_continuations(
    terminal: &Terminal<'_, '_>,
    replay: &mut Vec<u8>,
) -> Result<(), String> {
    let cols = terminal.cols().map_err(vt_error("read terminal columns"))?;
    let rows = terminal.rows().map_err(vt_error("read terminal rows"))?;
    for y in 1..rows {
        let first = terminal
            .grid_ref(Point::Active(PointCoordinate {
                x: 0,
                y: u32::from(y),
            }))
            .map_err(vt_error("read wrapped terminal row"))?;
        if !first
            .row()
            .and_then(|row| row.is_wrap_continuation())
            .map_err(vt_error("read terminal wrap continuation"))?
            || !row_is_plain_blank(terminal, y)?
        {
            continue;
        }
        append_cursor_cell(terminal, cols - 1, y - 1, replay)?;
        replay.extend_from_slice(b"\x1b[0m\x1b[0\x22q\x1b]8;;\x1b\\ \x08\x1b[X");
    }
    Ok(())
}

fn row_is_plain_blank(terminal: &Terminal<'_, '_>, y: u16) -> Result<bool, String> {
    for x in 0..terminal.cols().map_err(vt_error("read terminal columns"))? {
        let cell = terminal
            .grid_ref(Point::Active(PointCoordinate { x, y: u32::from(y) }))
            .and_then(|grid| grid.cell())
            .map_err(vt_error("read terminal blank-row cell"))?;
        if cell.has_text().map_err(vt_error("inspect cell text"))?
            || cell
                .has_styling()
                .map_err(vt_error("inspect cell styling"))?
            || cell
                .has_hyperlink()
                .map_err(vt_error("inspect cell hyperlink"))?
            || cell
                .is_protected()
                .map_err(vt_error("inspect cell protection"))?
        {
            return Ok(false);
        }
    }
    Ok(true)
}

fn last_osc8(bytes: &[u8]) -> Option<Vec<u8>> {
    let start = bytes.windows(4).rposition(|window| window == b"\x1b]8;")?;
    let terminator = bytes[start + 4..]
        .windows(2)
        .position(|window| window == b"\x1b\\")?;
    let end = start + 4 + terminator + 2;
    let sequence = &bytes[start..end];
    let payload = &sequence[4..sequence.len() - 2];
    let uri_start = payload.iter().position(|byte| *byte == b';')? + 1;
    (uri_start < payload.len()).then(|| sequence.to_vec())
}

fn append_hyperlink_cells(terminal: &Terminal<'_, '_>, replay: &mut Vec<u8>) -> Result<(), String> {
    for y in 0..terminal.rows().map_err(vt_error("read terminal rows"))? {
        for x in 0..terminal.cols().map_err(vt_error("read terminal columns"))? {
            let grid = terminal
                .grid_ref(Point::Active(PointCoordinate { x, y: u32::from(y) }))
                .map_err(vt_error("read terminal hyperlink cell"))?;
            if !grid
                .cell()
                .and_then(|cell| cell.has_hyperlink())
                .map_err(vt_error("inspect terminal hyperlink cell"))?
            {
                continue;
            }
            let graphemes = read_graphemes(&grid)?;
            if graphemes.is_empty() {
                continue;
            }
            let uri = read_hyperlink(&grid)?;
            replay.extend_from_slice(format!("\x1b[{};{}H", y + 1, x + 1).as_bytes());
            replay.extend_from_slice(
                style_sequence(grid.style().map_err(vt_error("read terminal cell style"))?)
                    .as_bytes(),
            );
            replay.extend_from_slice(b"\x1b]8;;");
            replay.extend_from_slice(&uri);
            replay.extend_from_slice(b"\x1b\\");
            for grapheme in graphemes {
                let mut encoded = [0; 4];
                replay.extend_from_slice(grapheme.encode_utf8(&mut encoded).as_bytes());
            }
            replay.extend_from_slice(b"\x1b]8;;\x1b\\");
        }
    }
    Ok(())
}

fn read_graphemes(grid: &libghostty_vt::screen::GridRef<'_>) -> Result<Vec<char>, String> {
    let mut output = Vec::new();
    loop {
        match grid.graphemes(&mut output) {
            Ok(length) => {
                output.truncate(length);
                return Ok(output);
            }
            Err(Error::OutOfSpace { required }) => output.resize(required, '\0'),
            Err(error) => return Err(format!("Failed to read terminal graphemes: {error}")),
        }
    }
}

fn read_hyperlink(grid: &libghostty_vt::screen::GridRef<'_>) -> Result<Vec<u8>, String> {
    let mut output = Vec::new();
    loop {
        match grid.hyperlink_uri(&mut output) {
            Ok(length) => {
                output.truncate(length);
                return Ok(output);
            }
            Err(Error::OutOfSpace { required }) => output.resize(required, 0),
            Err(error) => return Err(format!("Failed to read terminal hyperlink: {error}")),
        }
    }
}

fn style_sequence(style: Style) -> String {
    let mut codes = vec!["0".to_string()];
    if style.bold {
        codes.push("1".to_string());
    }
    if style.faint {
        codes.push("2".to_string());
    }
    if style.italic {
        codes.push("3".to_string());
    }
    match style.underline {
        Underline::None => {}
        Underline::Single => codes.push("4".to_string()),
        Underline::Double => codes.push("4:2".to_string()),
        Underline::Curly => codes.push("4:3".to_string()),
        Underline::Dotted => codes.push("4:4".to_string()),
        Underline::Dashed => codes.push("4:5".to_string()),
        _ => {}
    }
    if style.blink {
        codes.push("5".to_string());
    }
    if style.inverse {
        codes.push("7".to_string());
    }
    if style.invisible {
        codes.push("8".to_string());
    }
    if style.strikethrough {
        codes.push("9".to_string());
    }
    if style.overline {
        codes.push("53".to_string());
    }
    push_color(&mut codes, style.fg_color, "38", 30, 90);
    push_color(&mut codes, style.bg_color, "48", 40, 100);
    push_color(&mut codes, style.underline_color, "58", 0, 0);
    format!("\x1b[{}m", codes.join(";"))
}

fn push_color(
    codes: &mut Vec<String>,
    color: StyleColor,
    extended_prefix: &str,
    normal_base: u8,
    bright_base: u8,
) {
    match color {
        StyleColor::None => {}
        StyleColor::Palette(index) => {
            let index = index.0;
            if normal_base != 0 && index < 8 {
                codes.push((normal_base + index).to_string());
            } else if bright_base != 0 && index < 16 {
                codes.push((bright_base + index - 8).to_string());
            } else {
                codes.push(format!("{extended_prefix};5;{index}"));
            }
        }
        StyleColor::Rgb(color) => codes.push(format!(
            "{extended_prefix};2;{};{};{}",
            color.r, color.g, color.b
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn theme() -> TerminalColorTheme {
        TerminalColorTheme {
            foreground: "#eeeeee".to_string(),
            background: "#111111".to_string(),
            palette: vec!["#000000".to_string(); 16],
        }
    }

    /// The engine is where the product policy becomes physical retention. If
    /// this passes, no runtime can silently keep a different amount of history
    /// than the service committed.
    #[test]
    fn the_engine_retains_history_according_to_the_policy_it_was_given() {
        let feed_lines = |engine: &mut VtReplayEngine| {
            for _ in 0..3_000 {
                engine.feed(b"x\r\n");
            }
        };

        let mut none =
            VtReplayEngine::new(80, 24, &theme(), TerminalRetentionPolicy::from_bytes(0))
                .expect("engine");
        feed_lines(&mut none);
        assert_eq!(none.scrollback_rows().expect("rows"), 0);

        let mut budgeted =
            VtReplayEngine::new(80, 24, &theme(), TerminalRetentionPolicy::default())
                .expect("engine");
        feed_lines(&mut budgeted);
        assert!(budgeted.scrollback_rows().expect("rows") > 0);
    }

    /// A child that owns its colors keeps them when the user changes the app
    /// theme. `compat.rs` proves the child's OSC 4/10/11 state is readable, so
    /// a theme apply that overwrites it is discarding known state, not missing
    /// it. This test states the contract the end-state plan depends on; it
    /// records where today's engine does not meet it.
    #[test]
    fn a_theme_change_does_not_discard_colors_the_child_set_for_itself() {
        let mut engine =
            VtReplayEngine::new(20, 5, &theme(), TerminalRetentionPolicy::default()).unwrap();

        // The child claims a background, a foreground, and one palette slot.
        engine.feed(b"\x1b]11;#204060\x1b\\\x1b]10;#a0b0c0\x1b\\\x1b]4;1;#010203\x1b\\");

        let child_bg = RgbColor {
            r: 0x20,
            g: 0x40,
            b: 0x60,
        };
        let child_fg = RgbColor {
            r: 0xa0,
            g: 0xb0,
            b: 0xc0,
        };
        let child_slot = RgbColor {
            r: 0x01,
            g: 0x02,
            b: 0x03,
        };
        assert_eq!(engine.terminal.bg_color().unwrap(), Some(child_bg));
        assert_eq!(engine.terminal.fg_color().unwrap(), Some(child_fg));
        assert_eq!(
            engine
                .terminal
                .color_palette()
                .unwrap()
                .get(PaletteIndex(1)),
            child_slot
        );

        // The user switches the app theme. Nothing about that is a statement
        // about the colors the child chose.
        let new_theme = TerminalColorTheme {
            foreground: "#ffffff".to_string(),
            background: "#000000".to_string(),
            palette: vec!["#fefefe".to_string(); 16],
        };
        engine.set_theme(&new_theme).expect("apply theme");

        assert_eq!(
            engine.terminal.bg_color().unwrap(),
            Some(child_bg),
            "the child's OSC 11 background survives an app theme change"
        );
        assert_eq!(
            engine.terminal.fg_color().unwrap(),
            Some(child_fg),
            "the child's OSC 10 foreground survives an app theme change"
        );
        assert_eq!(
            engine
                .terminal
                .color_palette()
                .unwrap()
                .get(PaletteIndex(1)),
            child_slot,
            "the child's OSC 4 palette slot survives an app theme change"
        );

        // Guard against a vacuous pass. The three assertions above are only
        // meaningful if the theme apply actually did something, so prove it
        // reached the layer underneath the child's overrides.
        assert_eq!(
            engine.terminal.default_bg_color().unwrap(),
            Some(RgbColor {
                r: 0x00,
                g: 0x00,
                b: 0x00
            }),
            "the theme reached the host default layer beneath the child override"
        );
        assert_eq!(
            engine
                .terminal
                .color_palette()
                .unwrap()
                .get(PaletteIndex(2)),
            RgbColor {
                r: 0xfe,
                g: 0xfe,
                b: 0xfe
            },
            "a palette slot the child never claimed does follow the new theme"
        );
    }

    /// `RuntimeActor::resize` and `set_theme` both publish a replay, and the
    /// client installs one by calling `term.reset()` first. This test was
    /// written to show that a replay drops history. It does not: the replay
    /// carries every retained row. What a resize actually costs is the
    /// re-encoding of the whole retained buffer into ANSI, on every resize
    /// step and every theme change. Recorded here so no plan re-asserts a
    /// content loss that the engine does not have.
    #[test]
    fn a_replay_re_encodes_every_retained_row_so_its_cost_scales_with_history() {
        let mut engine =
            VtReplayEngine::new(20, 5, &theme(), TerminalRetentionPolicy::default()).unwrap();
        for line in 0..60 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }

        let retained = engine.scrollback_rows().expect("rows");
        assert!(
            retained > 0,
            "the engine retained scrolled-off rows, so history exists to lose"
        );

        let replay = engine.replay().expect("replay");
        let contains = |needle: &str| {
            replay
                .windows(needle.len())
                .any(|window| window == needle.as_bytes())
        };

        let missing: Vec<usize> = (0..60).filter(|n| !contains(&format!("line{n}"))).collect();
        assert!(
            missing.is_empty(),
            "the replay carries every retained row, not only the active screen; \
             missing rows would be {missing:?}"
        );

        // The cost is size, not loss. A replay is the whole retained buffer
        // re-encoded as ANSI, and resize and theme change each produce one.
        let bytes_per_row = replay.len() / (retained + 5);
        assert!(
            bytes_per_row > 0,
            "a replay re-encodes every retained row, so its size scales with \
             retention rather than with the screen"
        );
    }

    #[test]
    fn rejects_zero_dimensions_before_parser_allocation() {
        assert!(validate_dimensions(0, 24).is_err());
        assert!(validate_dimensions(80, 0).is_err());
    }

    /// The text of the row an anchor names, read back through the same reads a
    /// client has.
    fn anchored_text(engine: &VtReplayEngine, anchor: &TerminalAnchor) -> String {
        if let Some(at) = anchor.history {
            let window = engine.project_history(at.row, 1).expect("history reads");
            return window.rows[0].text().trim_end().to_string();
        }
        let at = anchor.active.expect("a retained anchor is named somewhere");
        // The viewport is the active area while nothing scrolled it away.
        engine.project().expect("the projection reads").viewport[at.row as usize]
            .text()
            .trim_end()
            .to_string()
    }

    /// The claim area 03 rests on: a client can keep pointing at one line
    /// without holding a row number, because row numbers move and the anchor
    /// moves with the line instead.
    #[test]
    fn an_anchor_follows_its_line_through_scrolling_and_resize() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::default()).unwrap();
        engine.feed(b"anchored\r\n");

        let anchor = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 0, row: 0 })
            .expect("the host anchors a cell");
        assert!(anchor.retained);
        assert_eq!(anchored_text(&engine, &anchor), "anchored");

        for line in 0..8 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }
        let scrolled = engine
            .resolve_anchor(anchor.id)
            .expect("the anchor reads")
            .expect("the host still holds the handle");
        assert!(scrolled.retained);
        assert_ne!(
            scrolled.active, anchor.active,
            "the line is no longer where it was"
        );
        assert_eq!(anchored_text(&engine, &scrolled), "anchored");

        engine.resize(24, 3).expect("the engine resizes");
        let reflowed = engine
            .resolve_anchor(anchor.id)
            .expect("the anchor reads")
            .expect("the host still holds the handle");
        assert!(reflowed.retained);
        assert_eq!(
            anchored_text(&engine, &reflowed),
            "anchored",
            "reflow moved the line and the anchor went with it"
        );
    }

    /// A history budget small enough that eviction happens inside a test.
    ///
    /// Measured, not chosen: at the 80-column geometry below it retains 655
    /// rows, so the 3,000 lines the test writes evict the oldest several times
    /// over. It is a test input and says nothing about what the product offers.
    const EVICTING_BUDGET_BYTES: usize = 64 * 1024;

    #[test]
    fn an_evicted_anchor_says_so_instead_of_naming_another_line() {
        let mut engine = VtReplayEngine::new(
            80,
            3,
            &theme(),
            TerminalRetentionPolicy::from_bytes(EVICTING_BUDGET_BYTES),
        )
        .unwrap();
        engine.feed(b"oldest\r\n");
        for line in 0..20 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }
        let anchor = engine
            .anchor(
                ProjectedSpace::History,
                ProjectedPoint { column: 0, row: 0 },
            )
            .expect("the host anchors a cell");
        assert!(anchor.retained);
        assert!(
            anchor.loss_reported,
            "history holds lines here, so a lost line is evicted from a page and reported"
        );
        assert_eq!(anchored_text(&engine, &anchor), "oldest");

        for line in 0..3_000 {
            engine.feed(format!("x{line}\r\n").as_bytes());
        }
        assert_ne!(
            engine.project_history(0, 1).unwrap().rows[0]
                .text()
                .trim_end(),
            "oldest",
            "history row 0 is a different line now, which is why it is not an identity"
        );

        let evicted = engine
            .resolve_anchor(anchor.id)
            .expect("the anchor reads")
            .expect("the handle is still answerable");
        assert!(
            !evicted.retained,
            "the line left the terminal and the anchor reports it"
        );
        assert!(evicted.loss_reported);
        assert_eq!(evicted.history, None);
        assert_eq!(evicted.screen, None);
        assert_eq!(evicted.active, None);

        // A row number would name whatever moved in. A handle is never reused,
        // so it cannot.
        let fresh = engine
            .anchor(
                ProjectedSpace::History,
                ProjectedPoint { column: 0, row: 0 },
            )
            .expect("the host anchors a cell");
        assert_ne!(fresh.id, anchor.id);
    }

    /// Where the anchor cannot be trusted, and why the limit is recorded rather
    /// than worked around.
    ///
    /// With no history budget, a line that scrolls off is not evicted from
    /// history; there is no history to evict it from. The pinned parser keeps
    /// the tracked reference on the active row instead, so the anchor names the
    /// line that replaced the anchored one and reports itself retained. A
    /// client on a zero-retention terminal therefore cannot anchor a line it
    /// expects to scroll away. If a later revision of the parser reports this,
    /// this test fails and the limit is lifted.
    ///
    /// The host does not leave a client to discover this: the anchor says its
    /// loss is not reported, so `retained` is not to be believed on it.
    #[test]
    fn with_no_history_a_scrolled_off_anchor_names_the_line_that_replaced_it() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::from_bytes(0)).unwrap();
        engine.feed(b"gone\r\n");
        let anchor = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 0, row: 0 })
            .expect("the host anchors a cell");
        assert!(
            !anchor.loss_reported,
            "no page can hold a line here, so no loss can be reported"
        );
        assert_eq!(anchored_text(&engine, &anchor), "gone");

        for line in 0..6 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }
        assert_eq!(engine.scrollback_rows().unwrap(), 0, "nothing is retained");

        let stale = engine
            .resolve_anchor(anchor.id)
            .expect("the anchor reads")
            .expect("the handle is still answerable");
        assert!(stale.retained);
        assert_eq!(stale.active, Some(ProjectedPoint { column: 0, row: 0 }));
        assert_ne!(
            anchored_text(&engine, &stale),
            "gone",
            "the anchored line is gone and the parser did not say so"
        );
        assert!(
            !stale.loss_reported,
            "the same anchor that reports itself retained also reports that its \
             loss cannot be seen, which is the fact a client acts on"
        );
    }

    /// The host declares what it knows about loss instead of guessing at it, so
    /// the fact tracks the terminal rather than the moment the anchor was made.
    ///
    /// A terminal that has not yet scrolled a line into history has proved
    /// nothing about retention, so it says loss is not reported. It corrects
    /// itself as soon as a page holds a line, for anchors made before that too.
    #[test]
    fn a_terminal_reports_loss_once_a_page_holds_a_line() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::default()).unwrap();
        engine.feed(b"first\r\n");
        assert_eq!(engine.scrollback_rows().unwrap(), 0);

        let anchor = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 0, row: 0 })
            .expect("the host anchors a cell");
        assert!(
            !anchor.loss_reported,
            "nothing has been retained yet, so nothing proves a loss would be reported"
        );

        for line in 0..6 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }
        assert!(engine.scrollback_rows().unwrap() > 0);

        let resolved = engine
            .resolve_anchor(anchor.id)
            .expect("the anchor reads")
            .expect("the host still holds the handle");
        assert!(
            resolved.loss_reported,
            "the same anchor corrects itself once history holds a line"
        );
        assert_eq!(anchored_text(&engine, &resolved), "first");
    }

    /// The parser reads a history coordinate on into the active area instead of
    /// stopping at the end of history, so asking for history row 0 on a
    /// terminal with no history would pin a live row and call it history.
    #[test]
    fn a_history_anchor_past_the_end_of_history_is_refused() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::default()).unwrap();
        engine.feed(b"live\r\n");
        assert_eq!(engine.scrollback_rows().unwrap(), 0);
        engine
            .anchor(
                ProjectedSpace::History,
                ProjectedPoint { column: 0, row: 0 },
            )
            .expect_err("there is no history row to anchor");
        assert_eq!(engine.anchor_count(), 0);

        // The same row is anchorable in the space that actually names it.
        engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 0, row: 0 })
            .expect("the live row is anchorable as a live row");

        for line in 0..6 {
            engine.feed(format!("line{line}\r\n").as_bytes());
        }
        let history_rows = engine.scrollback_rows().unwrap();
        assert!(history_rows > 0);
        engine
            .anchor(
                ProjectedSpace::History,
                ProjectedPoint {
                    column: 0,
                    row: history_rows as u32 - 1,
                },
            )
            .expect("the last retained row is anchorable");
        engine
            .anchor(
                ProjectedSpace::History,
                ProjectedPoint {
                    column: 0,
                    row: history_rows as u32,
                },
            )
            .expect_err("one row past the end is the active area, not history");
    }

    #[test]
    fn the_host_holds_anchors_only_while_a_client_asks_it_to() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::default()).unwrap();
        engine.feed(b"pinned\r\n");
        assert_eq!(engine.anchor_count(), 0);

        let first = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 0, row: 0 })
            .unwrap();
        let second = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 2, row: 0 })
            .unwrap();
        assert_eq!(engine.anchor_count(), 2);

        assert!(engine.release_anchor(first.id));
        assert!(
            !engine.release_anchor(first.id),
            "releasing twice is answered rather than repeated"
        );
        assert!(engine.resolve_anchor(first.id).unwrap().is_none());
        assert!(engine.resolve_anchor(second.id).unwrap().is_some());
        assert_eq!(engine.anchor_count(), 1);
    }

    /// The other half of the claim: what crosses a boundary is a number and
    /// coordinates, with nothing of the parser in it.
    #[test]
    fn an_anchor_round_trips_as_json() {
        let mut engine =
            VtReplayEngine::new(12, 3, &theme(), TerminalRetentionPolicy::default()).unwrap();
        engine.feed(b"anchored\r\n");
        let anchor = engine
            .anchor(ProjectedSpace::Active, ProjectedPoint { column: 3, row: 0 })
            .unwrap();

        let json = serde_json::to_string(&anchor).expect("the anchor serializes");
        assert!(
            json.contains("\"lossReported\""),
            "a client reads whether loss is reported off the wire: {json}"
        );
        let restored: TerminalAnchor =
            serde_json::from_str(&json).expect("the anchor deserializes");
        assert_eq!(restored, anchor);
    }

    #[test]
    fn parses_output_before_replay_and_answers_queries_once() {
        let mut engine =
            VtReplayEngine::new(20, 5, &theme(), TerminalRetentionPolicy::default()).unwrap();
        let responses = engine.feed(b"early\x1b[2;4H\x1b[6n");

        assert_eq!(responses, b"\x1b[2;4R");
        assert!(engine
            .replay()
            .unwrap()
            .windows(b"early".len())
            .any(|window| window == b"early"));
    }
}
