/** The public Workspace capability entrypoint for TypeScript-only plugins. */
export {
  WORKSPACE_CATALOG_SCHEMA_VERSION,
  WORKSPACE_DOCUMENT_SCHEMA_VERSION,
  WORKSPACE_PERSISTENCE_SCHEMA_VERSION,
  workspaceService,
} from "../protocol/workspace.ts";
export type {
  CloseWorkspaceViewCommand,
  FocusWorkspaceViewCommand,
  InspectWorkspaceInput,
  MoveWorkspaceViewCommand,
  MutateWorkspaceInput,
  OpenWorkspaceViewCommand,
  ResetWorkspaceCommand,
  SelectWorkspaceViewCommand,
  SplitWorkspaceViewCommand,
  UiWorkspaceDocument,
  WorkspaceCatalogSnapshot,
  WorkspaceCloseBehavior,
  WorkspaceCommand,
  WorkspaceErrorCode,
  WorkspaceFloatingStack,
  WorkspaceInspection,
  WorkspaceMutationResult,
  WorkspaceNode,
  WorkspaceObservation,
  WorkspaceObservationScope,
  WorkspacePersistedRecord,
  WorkspacePlacementIntent,
  WorkspaceResourceReference,
  WorkspaceRevision,
  WorkspaceService,
  WorkspaceSplitNode,
  WorkspaceStackNode,
  WorkspaceViewAvailability,
  WorkspaceViewCardinality,
  WorkspaceViewDefinition,
  WorkspaceViewInspection,
  WorkspaceViewInstance,
  WorkspaceViewPlacement,
  WorkspaceViewPresentationRef,
  WorkspaceViewScope,
  WorkspaceViewStatePolicy,
} from "../protocol/workspace.ts";
