show:
    node bin/version.mjs show

check:
    node bin/version.mjs check

next part:
    node bin/version.mjs next {{part}}

set version:
    node bin/version.mjs set {{version}}

verify-release:
    node bin/version.mjs verify-release

sync:
    node bin/version.mjs sync
