export type {
  ContributionId,
  ModuleId,
  PanelIconDescriptor,
  PanelUnavailableMetadata,
  ProjectRef,
} from "./protocol/panels";
export type {
  ModulePanelProps,
  PanelHostPort,
} from "./host/panels";
export type { PanelContribution } from "./module/panels";

export type { CommandInvocationContext } from "./host/commands";
export type { CommandContribution } from "./module/commands";

export type {
  ModuleAppearanceSnapshot,
  ModuleManagedTerminalSessionLaunchRequest,
  ModuleManagedTerminalStartContext,
  ModuleManagedTerminalStartResult,
  ModuleNotice,
  ModuleNoticeAction,
  ModuleNoticeOptions,
  ModuleSettingsSnapshot,
  ModuleSkillRef,
  ModuleSkillsSnapshot,
  ModuleTerminalColorTheme,
  ModuleTerminalDimensions,
  ModuleTerminalId,
  ModuleJsonValue,
  ModuleTerminalPresentationSnapshot,
  ModuleTerminalSession,
  ModuleTerminalSessionBadge,
  ModuleTerminalSessionExitReason,
  ModuleTerminalSessionIcon,
  ModuleTerminalSessionLaunchRequest,
  ModuleTerminalSessionLifecycleEvent,
  ModuleTerminalSessionObservation,
  ModuleTerminalSessionObservationEvent,
  ModuleTerminalSessionPresentation,
  ModuleTerminalSessionUpdate,
} from "./protocol/services";
export type {
  ModuleAppearancePort,
  ModuleExternalLinksPort,
  ModuleHostServices,
  ModuleNoticesPort,
  ModuleSettingsPort,
  ModuleSkillsPort,
  ModuleTerminalPresentationPort,
  ModuleTerminalSessionsPort,
} from "./host/services";
export { defineSemanticService } from "./protocol/semanticServices.ts";
export type {
  ModuleActivationContext,
  ModuleActivationId,
  ModuleActivationIdentity,
  SemanticCancellation,
  SemanticCleanup,
  SemanticCorrelationId,
  SemanticEventLease,
  SemanticEventRecord,
  SemanticEventSource,
  SemanticLeaseId,
  SemanticOrderedStream,
  SemanticOwnedLease,
  SemanticRequestCancellation,
  SemanticRequestOperation,
  SemanticRequestOptions,
  SemanticRequestOutcome,
  SemanticRequestPolicy,
  SemanticRequestRetry,
  SemanticResult,
  SemanticServiceAccess,
  SemanticServiceError,
  SemanticServiceReference,
  SemanticStreamAttachRequest,
  SemanticStreamAttachment,
  SemanticStreamAttachmentId,
  SemanticStreamDelivery,
  SemanticStreamDisconnect,
  SemanticStreamFrame,
  SemanticStreamGap,
} from "./protocol/semanticServices";
export type {
  AnySemanticServiceProvider,
  SemanticServiceProvider,
  SemanticServiceProviderContext,
} from "./host/semanticServices";
export { processesService } from "./protocol/processes.ts";
export type {
  CommandInspection,
  InspectCommandInput,
  InspectListeningProcessesInput,
  ListeningProcessInspection,
  ProcessesErrorCode,
  ProcessesService,
  ProcessInspectionId,
  TerminateInspectedProcessInput,
  TerminatedProcess,
} from "./protocol/processes";
export { projectDocumentsService } from "./protocol/projectDocuments.ts";
export type {
  DiscoverProjectDocumentsInput,
  ProjectDocument,
  ProjectDocumentRevision,
  ProjectDocumentsErrorCode,
  ProjectDocumentsService,
  ReadProjectDocumentInput,
  WriteProjectDocumentInput,
} from "./protocol/projectDocuments";
export { gitService } from "./protocol/git.ts";
export type {
  GitBranchInput,
  GitChangedFile,
  GitCommitInput,
  GitCreatedWorktree,
  GitCreateWorktreeInput,
  GitDiffStat,
  GitErrorCode,
  GitFileInput,
  GitMutationReceipt,
  GitProjectInput,
  GitReadDiffInput,
  GitReadFileInput,
  GitRepositoryChanged,
  GitRepositoryChangeScope,
  GitRepositoryStatus,
  GitService,
  GitTextResult,
  GitWorktree,
} from "./protocol/git";
export { skillId, skillInstallationService } from "./protocol/skillInstallation.ts";
export type {
  InstallSkillInput,
  InspectSkillsInput,
  RemoveSkillInput,
  SkillDescriptor,
  SkillId,
  SkillInspection,
  SkillInstallationErrorCode,
  SkillInstallationService,
  SkillMutationReceipt,
} from "./protocol/skillInstallation";
export { credentialId, credentialStoreService } from "./protocol/credentials.ts";
export type {
  CredentialGrant,
  CredentialId,
  CredentialStatus,
  CredentialStoreErrorCode,
  CredentialStoreService,
  DeleteCredentialInput,
  InspectCredentialInput,
  SaveCredentialInput,
} from "./protocol/credentials";
export {
  ASSISTANT_LAUNCH_GRANTS,
  assistantLaunchService,
  assistantProviderId,
  assistantSessionId,
} from "./protocol/assistantLaunch.ts";
export type {
  AssistantIdentityState,
  AssistantLaunchErrorCode,
  AssistantLaunchGrant,
  AssistantLaunchService,
  AssistantModelCatalog,
  AssistantProviderConfiguration,
  AssistantProviderId,
  AssistantProviderSettings,
  AssistantRecoveryRecord,
  AssistantSessionChanged,
  AssistantSessionChangeKind,
  AssistantSessionId,
  AssistantSessionInput,
  AssistantSessionMode,
  AssistantSessionObservationScope,
  AssistantTerminalStartContext,
  InspectAssistantModelsInput,
  InspectAssistantProviderConfigurationInput,
  RecordAssistantLabelInput,
  RecordAssistantPlacementInput,
  ResumeAssistantSessionInput,
  SaveAssistantProviderConfigurationInput,
  StartAssistantSessionInput,
  StartedAssistantSession,
} from "./protocol/assistantLaunch";
export { usageSourcesService } from "./protocol/usageSources.ts";
export type {
  InspectUsageSourceInput,
  RefreshUsageSourcesInput,
  UsageConfidence,
  UsageCostKind,
  UsageProvider,
  UsageProviderObservation,
  UsageProviderWindow,
  UsageSourceDescriptor,
  UsageSourceDataset,
  UsageSourceInspection,
  UsageSourceKind,
  UsageSourceObservationScope,
  UsageSourceRecord,
  UsageSourceRefreshReceipt,
  UsageSourcesChanged,
  UsageSourcesErrorCode,
  UsageSourcesGrant,
  UsageSourcesService,
  UsageSourceType,
} from "./protocol/usageSources";
export { pluginDataService } from "./protocol/pluginData.ts";
export type {
  MigratePluginDataRecordsInput,
  PluginDataErrorCode,
  PluginDataGrant,
  PluginDataMigrationProvenance,
  PluginDataMigrationReceipt,
  PluginDataMigrationWrite,
  PluginDataRecord,
  PluginDataRevision,
  PluginDataScope,
  PluginDataService,
  ReadPluginDataRecordInput,
  WritePluginDataRecordInput,
} from "./protocol/pluginData";

export type {
  ProjectActionSurfacePosition,
  ProjectFacts,
  ProjectLayoutSlot,
  SettingsSlot,
} from "./protocol/surfaces";
export type {
  GlobalSurfaceContributionProps,
  ProjectActionSurfaceHost,
  ProjectActionSurfaceProps,
  ProjectLayoutContributionProps,
  ProjectNavigationContributionProps,
  SettingsContributionProps,
  SidebarContributionProps,
} from "./host/surfaces";
export type {
  GlobalNavigationContribution,
  GlobalSurfaceContribution,
  ModuleProjectLifecycle,
  ProjectAction,
  ProjectActionContribution,
  ProjectActionGroup,
  ProjectCommandAction,
  ProjectFactsProviderContribution,
  ProjectImportContribution,
  ProjectLayoutContribution,
  ProjectNavigationContribution,
  ProjectSurfaceAction,
  SidebarContribution,
  SettingsContribution,
} from "./module/surfaces";

export type { ModuleHost } from "./host/module";
export type {
  ModuleDeactivation,
  ModuleScheduledTask,
  ShipctlModule,
  SkillsProviderContribution,
} from "./module/module";
export { defineShipctlPlugin } from "./module/plugins.ts";
export type {
  PluginArtifactDeclarations,
  PluginActivationInspection,
  PluginActivationStatus,
  PluginActivationView,
  PluginContributionDeclaration,
  PluginContributionFamily,
  PluginContributionInspection,
  PluginEffectInspection,
  PluginEffectKind,
  PluginRuntimeInspection,
  ShipctlPluginDefinition,
  ShipctlPluginRole,
} from "./module/plugins.ts";

export { terminalDriverId } from "./protocol/terminalHost.ts";
export type {
  RawTerminalAttachment,
  RawTerminalOccurrence,
  TerminalDriverId,
  TerminalHostDescriptor,
  TerminalHostLaunchRequest,
  TerminalHostLifecycle,
  TerminalHostLifecycleEvent,
} from "./protocol/terminalHost.ts";
export type {
  TerminalHostPort,
  TerminalPresentationProps,
} from "./host/terminalHost";
export type { TerminalPresentationProvider } from "./module/terminalHost";

export {
  TERMINAL_SESSION_GRANTS,
  TERMINAL_SESSIONS_ERROR_CODES,
  terminalSessionsService,
} from "./protocol/terminalSessions.ts";
export type {
  AttachTerminalBytesInput,
  FocusTerminalSessionInput,
  InspectTerminalSessionsInput,
  ResizeTerminalInput,
  StartTerminalSessionInput,
  StopTerminalSessionInput,
  TerminalByteFrame,
  TerminalByteStream,
  TerminalSessionGrant,
  TerminalSessionLifecycleScope,
  TerminalSessionsErrorCode,
  TerminalSessionsService,
  UpdateTerminalSessionInput,
  WriteTerminalInput,
} from "./protocol/terminalSessions.ts";

export {
  SEMANTIC_TERMINAL_GRANTS,
  SEMANTIC_TERMINALS_ERROR_CODES,
  semanticTerminalsService,
} from "./protocol/semanticTerminals.ts";
export type {
  AttachSemanticTerminalScreenInput,
  CreateSemanticTerminalAnchorInput,
  InputSemanticTerminalInput,
  InspectSemanticTerminalPasteInput,
  InspectSemanticTerminalPublicationInput,
  InspectSemanticTerminalSnapshotInput,
  ReadSemanticTerminalHistoryInput,
  ReleaseSemanticTerminalAnchorInput,
  ResizeSemanticTerminalInput,
  ResolveSemanticTerminalAnchorInput,
  SelectSemanticTerminalInput,
  SemanticTerminalAnchor,
  SemanticTerminalAnchorId,
  SemanticTerminalAttachmentId,
  SemanticTerminalCellWidth,
  SemanticTerminalColor,
  SemanticTerminalEffect,
  SemanticTerminalGrant,
  SemanticTerminalHistoryCell,
  SemanticTerminalHistoryRow,
  SemanticTerminalHistoryWindow,
  SemanticTerminalId,
  SemanticTerminalInput,
  SemanticTerminalModifiers,
  SemanticTerminalProjectedPoint,
  SemanticTerminalProjectedSpace,
  SemanticTerminalPrompt,
  SemanticTerminalPublicationStats,
  SemanticTerminalRevision,
  SemanticTerminalScreenAttachment,
  SemanticTerminalScreenFrame,
  SemanticTerminalScreenRow,
  SemanticTerminalScreenRun,
  SemanticTerminalScreenSnapshot,
  SemanticTerminalScreenState,
  SemanticTerminalScreenStream,
  SemanticTerminalSelectionMove,
  SemanticTerminalSelectionRequest,
  SemanticTerminalSelectionRow,
  SemanticTerminalSelectionSpan,
  SemanticTerminalSelectionState,
  SemanticTerminalsErrorCode,
  SemanticTerminalsService,
} from "./protocol/semanticTerminals.ts";

export {
  JSON_SCHEMA_DRAFT_2020_12,
  MESSAGE_CONTRACT_SCHEMA_VERSION,
  MESSAGE_DIAGNOSTIC_CODES,
  MESSAGE_SERVICE_ERROR_CODES,
  MessageContractParseError,
  messagesService,
  parseDeliveryReceipt,
  parseMessageDeclarations,
  parseMessageEnvelope,
  parseMessageObservation,
  parseMessageRouteSnapshot,
  parsePublishReceipt,
} from "./protocol/messages.ts";
export type {
  BroadcastMessagePublisher,
  BroadcastMessageSubscription,
  BroadcastRoute,
  BroadcastTopic,
  CapabilityPort,
  CapabilityPortHandler,
  DeliveryReceipt,
  DirectedChannel,
  DirectedMessageHandler,
  DirectedRoute,
  MessageDeclarations,
  MessageDiagnosticCode,
  MessageEnvelope,
  MessageObservation,
  MessageRef,
  MessageRouteSnapshot,
  MessageSchemaDescriptor,
  MessageServiceErrorCode,
  MessageTypeContract,
  MessageTypeId,
  ModuleMessageContributions,
  ModuleMessages,
  PublishMessageInput,
  PublishMessageOperation,
  PublishReceipt,
  RequestMessageInput,
  RequestMessageOperation,
  RouteEndpointRef,
  SendMessageInput,
  SendMessageOperation,
  WireBroadcastTopicDeclaration,
  WireCapabilityPortDeclaration,
  WireDirectedChannelDeclaration,
} from "./protocol/messages";

export {
  SCHEDULE_DIAGNOSTIC_CODES,
  SCHEDULE_INSPECTION_SCHEMA_VERSION,
  SCHEDULE_SCHEMA_VERSION,
  SCHEDULER_REGISTER_GRANT,
  SCHEDULER_SERVICE_ERROR_CODES,
  SCHEDULER_SERVICE_SCHEMA_VERSION,
  ScheduleInspectionParseError,
  parseScheduleInspection,
  schedulerService,
} from "./protocol/schedules.ts";
export type {
  InspectSchedulesInput,
  RegisterScheduleInput,
  RegisterScheduleOperation,
  ScheduleDefinitionInspection,
  ScheduleDeliveryOutcome,
  ScheduleDeliverySummary,
  ScheduleDiagnostic,
  ScheduleDiagnosticCode,
  ScheduleDiagnosticSeverity,
  ScheduleInspection,
  ScheduleLease,
  ScheduleLeaseInspection,
  ScheduleRegistrationTarget,
  ScheduleTarget,
  ScheduleTargetAvailability,
  ScheduleTargetKind,
  ScheduledDeliveryEvent,
  SchedulerService,
  SchedulerServiceErrorCode,
} from "./protocol/schedules";

export {
  CAPABILITY_CONTRACT_SCHEMA_VERSION,
  CAPABILITY_DIAGNOSTIC_CODES,
  CapabilityContractParseError,
  parseCapabilityManifest,
} from "./protocol/capabilities.ts";
export type {
  CapabilityAgentAccess,
  CapabilityAgentWatchAccess,
  CapabilityConsumerBinding,
  CapabilityDefinition,
  CapabilityDiagnosticCode,
  CapabilityEventDefinition,
  CapabilityManifest,
  CapabilityPortDefinition,
  CapabilityPortKind,
  CapabilityProviderBinding,
  CapabilityProviderCardinality,
  CapabilityProviderSelection,
  CapabilityReference,
  CapabilityScope,
  CapabilityStreamDefinition,
  CapabilitySurfaceBinding,
  CapabilityTopicDefinition,
} from "./protocol/capabilities";
