//! Canonical, storage-independent contracts for module control.
//!
//! The registry, local control endpoint, CLI, and frontend supervisor share
//! these values. They describe a desired configuration for one named running
//! instance; they never model Cargo feature selection or a source rebuild.

pub mod agent;
pub mod artifact;
pub mod artifact_snapshot;
pub mod codes;
pub mod contracts;
pub mod live;
pub mod registry;
pub mod repository;

pub use codes::{
    ARTIFACT_ADDED, ARTIFACT_DISABLED_INSPECTED, ARTIFACT_PACKED, ARTIFACT_PREFLIGHTED,
    BUILD_PROVENANCE, CAPABILITY_INSPECTED, CONTROL_CAPABILITY_UNAVAILABLE, DESIRED_STATE_ABSENT,
    INVALID_DESIRED_STATE, INVALID_DIAGNOSTIC, INVALID_IDENTITY, INVALID_JSON, MODULE_ABSENT,
    MODULE_ACTIVE, MODULE_STARTUP_FAILED, MODULE_UNOBSERVED, MUTATION_UNAVAILABLE,
    OPERATION_ABSENT, OPERATION_ACCEPTED, OPERATION_CAPABILITY_UNAVAILABLE, OPERATION_INSPECTED,
    RECONCILIATION_FAILED, REGISTRY_ABSENT, REGISTRY_ARTIFACT_IMMUTABLE,
    REGISTRY_ARTIFACT_REFERENCE_MISSING, REGISTRY_CONTRACT_INVALID, REGISTRY_DIAGNOSTICS_FAILED,
    REGISTRY_HEALTHY, REGISTRY_INSPECTED, REGISTRY_INTEGRITY_FAILED, REGISTRY_INVENTORY_ABSENT,
    REGISTRY_INVENTORY_MISMATCH, REGISTRY_INVENTORY_STALE, REGISTRY_JOURNAL_INCONSISTENT,
    REGISTRY_LISTED, REGISTRY_MIGRATION_FAILED, REGISTRY_REVISION_DISCONTINUOUS,
    REGISTRY_SCHEMA_UNSUPPORTED, REGISTRY_STATE_ROOT_INVALID, REGISTRY_TRANSACTION_FAILED,
    REGISTRY_UNREADABLE, REVISION_INVALID, REVISION_LAG, REVISION_OBSERVER_UNAVAILABLE,
    RUNTIME_DIAGNOSED, RUNTIME_INSPECTED, RUNTIME_OFFLINE, SCHEMA_VERSION_UNSUPPORTED,
    SECRET_LEAKAGE, SNAPSHOT_AVAILABLE, SNAPSHOT_INVALID, SNAPSHOT_UNAVAILABLE, UNKNOWN_FIELD,
    VERIFICATION_EXPECTATION_MODULE_MISMATCH, VERIFICATION_EXPECTATION_UNREADABLE,
    VERIFICATION_MATCHED, VERIFICATION_MISMATCH,
};
pub use contracts::{
    parse_contract_json, DesiredModuleState, Diagnostic, DiagnosticSeverity, ModuleContract,
    ModuleContractError, ModuleContribution, ModuleGrant, ModuleIdentity, ModuleInspection,
    ModuleLifecycleState, ModuleOperation, ModuleOperationKind, ModuleOperationPhase,
    ModuleOperationResult, ModuleRuntimeKind, ModuleSource, ModuleTransition, ObservedModuleState,
    RedactedEvidence, ResourceDrainState, ResourceLease, VerificationExpectation,
    VerificationObserved, VerificationResult, MODULE_CONTROL_SCHEMA_VERSION,
};
