/**
 * The paint plan against the host's own frame.
 *
 * `terminalScreenFixture.json` is generated by `terminal/contract.rs` from the
 * host parser, so the wide grapheme, the combining mark, the hyperlink run and
 * the wrapped row below are the host's facts rather than a fixture written to
 * suit the painter. The falsification this file carries is occupancy: a plan
 * that decided a span from the text it was given would disagree with the host
 * here, and every assertion about columns would move.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { decodeScreenState, type TerminalScreenModel } from "../terminalClientModel.ts";
import {
  hitTestTerminalCell,
  planTerminalPaint,
  type TerminalCellMetrics,
} from "../terminalCellPaint.ts";

const METRICS: TerminalCellMetrics = { cellWidth: 9, cellHeight: 18 };

const fixture = JSON.parse(
  readFileSync(new URL("../terminalScreenFixture.json", import.meta.url), "utf8"),
) as { state: unknown };

function hostScreen(change?: (state: Record<string, any>) => void): TerminalScreenModel {
  const state = structuredClone(fixture.state) as Record<string, any>;
  change?.(state);
  return decodeScreenState(state);
}

function spansOn(plan: ReturnType<typeof planTerminalPaint>, row: number) {
  return plan.spans.filter((span) => span.row === row);
}

test("a wide grapheme is painted once, across the two columns the host gave it", () => {
  const screen = hostScreen();
  const plan = planTerminalPaint(screen, { metrics: METRICS, repaint: "full" });

  // Row 1 of the host frame is "漢" (wide, with a spacer tail) then "é".
  const [wide, rest] = spansOn(plan, 1);
  assert.equal(wide.text, "漢");
  assert.equal(wide.column, 0);
  assert.equal(wide.columns, 2, "the host said wide; nothing here measured it");
  assert.equal(wide.cellColumns, 2);
  assert.equal(wide.x, 0);
  assert.equal(wide.width, 2 * METRICS.cellWidth);

  assert.equal(rest.column, 2, "the run after it starts where the host span ended");
  assert.equal(rest.cellColumns, 1, "a run never mixes cell widths");
  assert.equal(rest.x, 2 * METRICS.cellWidth);
  const hostCell = screen.viewport[1].cells[2].text;
  assert.equal(rest.text.startsWith(hostCell), true, "the run opens with the host's own cluster");

  assert.equal(
    spansOn(plan, 1).length,
    2,
    "the tail of the wide grapheme is not a cell of its own",
  );
  assert.equal(
    spansOn(plan, 1).reduce((columns, span) => columns + span.columns, 0),
    screen.columns,
    "the painted columns are the row's columns, no more and no fewer",
  );
});

test("the span of a grapheme does not follow the length of its text", () => {
  // Two mutations the host would never send together, each of which a painter
  // that measured text would get wrong in the opposite direction: a wide cell
  // holding one code point, and a narrow cell holding four.
  const screen = hostScreen((state) => {
    state.viewport[1].runs[0].glyphs[0] = "x";
    state.viewport[1].runs[2].glyphs[0] = "á̂̃";
  });
  const plan = planTerminalPaint(screen, { metrics: METRICS, repaint: "full" });
  const [wide, rest] = spansOn(plan, 1);

  assert.equal(wide.text, "x");
  assert.equal(wide.columns, 2, "a one-character glyph still owns the host's two columns");
  assert.equal(rest.column, 2);
  assert.equal(rest.text.startsWith("á̂̃"), true);
  assert.equal(
    rest.columns,
    screen.columns - 2,
    "a four-code-point cluster still owns the host's one column",
  );
});

test("runs break where style breaks and nowhere else", () => {
  const plan = planTerminalPaint(hostScreen(), { metrics: METRICS, repaint: "full" });

  // Row 0 is "$ " plain, then "bold" in bold and a colour, then blanks.
  const row = spansOn(plan, 0);
  assert.deepEqual(
    row.map((span) => [span.column, span.columns, span.text, span.bold]),
    [
      [0, 2, "$ ", false],
      [2, 4, "bold", true],
      [6, 34, " ".repeat(34), false],
    ],
  );
  assert.deepEqual(row[1].foreground, { r: 10, g: 20, b: 30 });

  // Row 2 carries an OSC 8 link on its first four cells.
  const link = spansOn(plan, 2);
  assert.equal(link[0].hyperlink, "https://example.com");
  assert.equal(link[0].text, "link");
  assert.equal(link[1].hyperlink, null);
});

test("the plan carries the host's colours and screen, and decides none of them", () => {
  const plan = planTerminalPaint(hostScreen(), { metrics: METRICS, repaint: "full" });

  assert.equal(plan.screen, "primary");
  assert.deepEqual(plan.defaultForeground, { r: 230, g: 230, b: 230 });
  assert.deepEqual(plan.defaultBackground, { r: 16, g: 16, b: 16 });
  assert.equal(plan.reverseVideo, false);
  assert.equal(plan.columns, 40);
  assert.equal(plan.rows, 8);
  assert.equal(plan.width, 40 * METRICS.cellWidth);
  assert.equal(plan.height, 8 * METRICS.cellHeight);

  const alternate = planTerminalPaint(
    hostScreen((state) => {
      state.screen = "alternate";
      state.modes.reverseVideo = true;
    }),
    { metrics: METRICS, repaint: "full" },
  );
  assert.equal(alternate.screen, "alternate");
  assert.equal(alternate.reverseVideo, true);
});

test("a partial frame paints the rows the host named, and a full repaint ignores damage", () => {
  const damaged = hostScreen((state) => {
    state.damage = { scope: "partial", rows: [2, 1, 1] };
  });

  const partial = planTerminalPaint(damaged, { metrics: METRICS, repaint: "damage" });
  assert.deepEqual(partial.paintedRows, [1, 2], "sorted and deduplicated for the painter");
  assert.deepEqual(
    [...new Set(partial.spans.map((span) => span.row))],
    [1, 2],
  );

  const full = planTerminalPaint(damaged, { metrics: METRICS, repaint: "full" });
  assert.deepEqual(full.paintedRows, [0, 1, 2, 3, 4, 5, 6, 7]);

  const clean = planTerminalPaint(
    hostScreen((state) => {
      state.damage = { scope: "clean", rows: [] };
    }),
    { metrics: METRICS, repaint: "damage" },
  );
  assert.deepEqual(clean.paintedRows, []);
  assert.deepEqual(clean.spans, []);
  assert.equal(clean.cursor?.row, 4, "a clean frame still says where the cursor is");
});

test("the cursor is drawn over the whole cell the host put it on", () => {
  const plan = planTerminalPaint(hostScreen(), { metrics: METRICS, repaint: "full" });
  assert.deepEqual(plan.cursor, {
    row: 4,
    column: 5,
    columns: 1,
    visible: true,
    shape: "block",
    x: 5 * METRICS.cellWidth,
    y: 4 * METRICS.cellHeight,
    width: METRICS.cellWidth,
    height: METRICS.cellHeight,
  });

  // On the tail of a wide grapheme, the cursor belongs to the grapheme.
  const onTail = planTerminalPaint(
    hostScreen((state) => {
      state.cursor = {
        column: 1,
        row: 1,
        visible: true,
        pendingWrap: false,
        shape: "block",
        blinking: false,
      };
    }),
    { metrics: METRICS, repaint: "full" },
  );
  assert.equal(onTail.cursor?.column, 0);
  assert.equal(onTail.cursor?.columns, 2);
  assert.equal(onTail.cursor?.width, 2 * METRICS.cellWidth);

  const hidden = planTerminalPaint(
    hostScreen((state) => {
      state.cursor.visible = false;
    }),
    { metrics: METRICS, repaint: "full" },
  );
  assert.equal(hidden.cursor?.visible, false);

  // The shape is the host's, and it reaches the plan unchanged: the rectangle
  // is the same cell either way, and what is filled inside it is the target's.
  const bar = planTerminalPaint(
    hostScreen((state) => {
      state.cursor.shape = "bar";
    }),
    { metrics: METRICS, repaint: "full" },
  );
  assert.equal(bar.cursor?.shape, "bar");
  assert.equal(bar.cursor?.width, METRICS.cellWidth);

  // A blink is the caller's clock. A cursor the host does not call blinking is
  // drawn whatever the caller's phase says, and one that does blink is not.
  const dark = hostScreen((state) => {
    state.cursor.blinking = true;
  });
  assert.equal(
    planTerminalPaint(dark, { metrics: METRICS, repaint: "full", cursorLit: false }).cursor?.visible,
    false,
  );
  assert.equal(
    planTerminalPaint(dark, { metrics: METRICS, repaint: "full", cursorLit: true }).cursor?.visible,
    true,
  );
  assert.equal(
    planTerminalPaint(hostScreen(), { metrics: METRICS, repaint: "full", cursorLit: false })
      .cursor?.visible,
    true,
    "a cursor the host does not call blinking has no phase to be dark in",
  );
});

test("a pixel resolves to the host cell that owns it, or to nothing", () => {
  const screen = hostScreen();
  const at = (x: number, y: number) => hitTestTerminalCell({ x, y }, screen, METRICS);

  assert.deepEqual(at(0, 0), { row: 0, column: 0 });
  assert.deepEqual(at(3 * 9 + 4, 2 * 18 + 5), { row: 2, column: 3 });

  // Both columns of the wide grapheme answer with the grapheme's own column.
  assert.deepEqual(at(2, 18), { row: 1, column: 0 });
  assert.deepEqual(at(9 + 2, 18), { row: 1, column: 0 });
  assert.deepEqual(at(18 + 2, 18), { row: 1, column: 2 });

  assert.equal(at(-1, 0), null);
  assert.equal(at(0, -1), null);
  assert.equal(at(40 * 9, 0), null, "past the last column is off the grid");
  assert.equal(at(0, 8 * 18), null, "past the last row is off the grid");
  assert.equal(hitTestTerminalCell({ x: 0, y: 0 }, screen, { cellWidth: 0, cellHeight: 18 }), null);
});
