/**
 * The client model against a frame the host actually wrote.
 *
 * `terminalScreenFixture.json` is generated by `terminal/contract.rs` from the
 * host's own parser and checked in. Every assertion below therefore fails when
 * the host renames a field or changes a shape, which is the only way a client
 * model that types rows and cells can be kept honest without a browser.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import {
  decodeScreenState,
  TerminalClientModel,
  TerminalModelDecodeError,
  type TerminalDamageModel,
  type TerminalModelState,
  type TerminalScreenFrame,
} from "../terminalClientModel.ts";
import { decodeTerminalEvent } from "../terminalEventDecoder.ts";

const fixture = JSON.parse(
  readFileSync(new URL("../terminalScreenFixture.json", import.meta.url), "utf8"),
) as Record<string, unknown>;

/** The fixture as the client receives it: through the fail-closed decoder. */
function hostFrame(): TerminalScreenFrame {
  const event = decodeTerminalEvent(structuredClone(fixture));
  assert.equal(event.event, "screen");
  if (event.event !== "screen") throw new Error("unreachable");
  return {
    sequence: event.sequence,
    revision: event.revision,
    state: event.state,
    effects: event.effects,
  };
}

/** The same frame with one thing changed, for the frames that must be refused. */
function damagedFrame(change: (state: Record<string, any>) => void): TerminalScreenFrame {
  const frame = hostFrame();
  const state = structuredClone(frame.state) as Record<string, any>;
  change(state);
  return { ...frame, state };
}

test("the model reads what the host wrote, and recomputes none of it", () => {
  const screen = decodeScreenState(hostFrame().state);

  assert.equal(screen.columns, 40);
  assert.equal(screen.rows, 8);
  assert.equal(screen.screen, "primary");
  assert.equal(screen.viewport.length, 8);

  const prompt = screen.viewport[0];
  assert.equal(prompt.prompt, "prompt");
  assert.equal(prompt.cells[2].text, "b");
  assert.equal(prompt.cells[2].bold, true);
  assert.deepEqual(prompt.cells[2].foreground, { r: 10, g: 20, b: 30 });
  assert.equal(prompt.cells[0].bold, false);
  assert.equal(prompt.cells[0].foreground, null);

  const graphemes = screen.viewport[1];
  assert.equal(graphemes.cells[0].text, "漢");
  assert.equal(graphemes.cells[0].width, "wide");
  assert.equal(graphemes.cells[1].width, "spacer_tail");
  assert.equal(graphemes.cells[1].text, "");
  assert.equal(graphemes.cells[2].text, "é");

  assert.equal(screen.viewport[2].cells[0].hyperlink, "https://example.com");
  assert.equal(screen.viewport[0].cells[0].hyperlink, null);

  assert.equal(screen.viewport[3].wrapped, true);
  assert.equal(screen.viewport[4].continuation, true);

  assert.equal(screen.cursor.pendingWrap, false);
  assert.equal(screen.cursor.visible, true);
  assert.equal(screen.modes.wraparound, true);
  assert.equal(screen.modes.bracketedPaste, false);
  assert.deepEqual(screen.colors.foreground, { r: 230, g: 230, b: 230 });
  assert.equal(screen.colors.palette.length, 16);
  assert.equal(screen.damage.scope, "full");
});

test("the occurrences arrive in the order the host reported them", () => {
  const model = new TerminalClientModel();
  assert.deepEqual(model.applyScreen(hostFrame()), { status: "committed" });
  assert.deepEqual(
    model.drainEffects().map((effect) => effect.kind),
    ["title", "bell"],
  );
  assert.deepEqual(model.drainEffects(), [], "an occurrence is delivered once");
});

test("a frame the host could not have written is refused whole", () => {
  const cases: [string, TerminalScreenFrame][] = [
    ["an unknown cell width", damagedFrame((s) => (s.viewport[0].cells[0].width = "huge"))],
    ["a missing cursor fact", damagedFrame((s) => delete s.cursor.pendingWrap)],
    ["a missing mode", damagedFrame((s) => delete s.modes.origin)],
    ["a colour channel out of range", damagedFrame((s) => (s.colors.palette[0].r = 300))],
    ["a row count the viewport contradicts", damagedFrame((s) => s.viewport.pop())],
    ["damage naming a row that does not exist", damagedFrame((s) => s.damage.rows.push(99))],
    ["an absent optional colour", damagedFrame((s) => delete s.viewport[0].cells[0].foreground)],
    ["a prompt mark the host does not use", damagedFrame((s) => (s.viewport[0].prompt = "later"))],
  ];

  for (const [what, frame] of cases) {
    const model = new TerminalClientModel();
    const outcome = model.applyScreen(frame);
    assert.equal(outcome.status, "rejected", what);
    assert.equal(outcome.status === "rejected" && outcome.reason, "invalid", what);
    assert.equal(model.state, null, `${what} left the model partly mutated`);
  }
});

test("a rejected frame leaves the committed state exactly as it was", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  const committed = model.state;
  assert.ok(committed);
  model.drainEffects();

  const outcome = model.applyScreen({
    ...damagedFrame((s) => (s.viewport[2].cells[0].width = "huge")),
    sequence: committed.sequence + 1,
  });
  assert.equal(outcome.status, "rejected");
  assert.equal(model.state, committed, "the model kept the state it had");
  assert.deepEqual(
    model.drainEffects(),
    [],
    "a refused frame delivers none of its occurrences either",
  );
});

test("a frame that is not newer than the committed one is stale, not applied", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  const outcome = model.applyScreen(hostFrame());
  assert.equal(outcome.status, "rejected");
  assert.equal(outcome.status === "rejected" && outcome.reason, "stale");
  assert.equal(model.state?.sequence, 12);
});

test("hiding and showing a surface changes presentation, not the model", () => {
  const model = new TerminalClientModel();
  const seen: [TerminalModelState, TerminalDamageModel][] = [];
  const surface = model.subscribe((state, damage) => seen.push([state, damage]));

  model.applyScreen(hostFrame());
  assert.equal(seen.length, 1);
  assert.equal(seen[0][1].scope, "full");

  // The surface goes away. The terminal does not.
  surface();
  const hidden = hostFrame();
  const next = model.applyScreen({ ...hidden, sequence: hidden.sequence + 1 });
  assert.deepEqual(next, { status: "committed" }, "output applies with nothing mounted");
  assert.equal(seen.length, 1, "an unmounted surface is not painted");

  // A new surface repaints from the model, with no host round trip.
  const repainted: [TerminalModelState, TerminalDamageModel][] = [];
  model.subscribe((state, damage) => repainted.push([state, damage]));
  assert.equal(repainted.length, 1);
  assert.equal(repainted[0][0].sequence, 13, "it is given the state that arrived while hidden");
  assert.equal(
    repainted[0][1].scope,
    "full",
    "a surface that has painted nothing repaints everything, whatever the frame said",
  );
  assert.equal(model.state, repainted[0][0], "one model, one identity, across both surfaces");
});

test("occurrences that arrive with no surface mounted still arrive once", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  const later = hostFrame();
  model.applyScreen({ ...later, sequence: 13, effects: [{ kind: "bell" }] });

  assert.deepEqual(
    model.drainEffects().map((effect) => effect.kind),
    ["title", "bell", "bell"],
    "nothing was dropped for want of a surface, and nothing was reordered",
  );
});

test("viewport intent survives a surface, and an exit does not end the model", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  model.setViewportIntent({ followBottom: false, historyAnchor: 42 });

  const surface = model.subscribe(() => {});
  surface();
  assert.deepEqual(model.viewportIntent, { followBottom: false, historyAnchor: 42 });

  model.noteExited();
  assert.equal(model.exited, true);
  assert.ok(model.state, "an ended terminal still shows what it printed");
});

test("disposal is deliberate and refuses everything after it", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  model.dispose();

  assert.equal(model.disposed, true);
  assert.equal(model.state, null);
  const outcome = model.applyScreen({ ...hostFrame(), sequence: 99 });
  assert.equal(outcome.status, "rejected");
  assert.equal(model.state, null);
});

test("the decoder throws where a caller decodes directly", () => {
  assert.throws(() => decodeScreenState({}), TerminalModelDecodeError);
  assert.throws(() => decodeScreenState(null), TerminalModelDecodeError);
});

test("moving the reading position is a change to what every surface shows", () => {
  const model = new TerminalClientModel();
  model.applyScreen(hostFrame());
  const seen: TerminalDamageModel[] = [];
  model.subscribe((_state, damage) => seen.push(damage));
  seen.length = 0;

  model.setViewportIntent({ followBottom: false, historyAnchor: 4 });
  assert.deepEqual(
    seen,
    [{ scope: "full", rows: [] }],
    "the rows above and below a scroll are not the rows the last frame described",
  );

  // The same position again is not a change, and does not cost a frame.
  model.setViewportIntent({ followBottom: false, historyAnchor: 4 });
  assert.equal(seen.length, 1);
});

test("a history window wakes the reader who is looking at it, and nobody else", () => {
  const window = {
    startRow: 0,
    historyRows: 6,
    rows: (structuredClone(fixture) as Record<string, any>).state.viewport.slice(0, 2),
  };

  const following = new TerminalClientModel();
  following.applyScreen(hostFrame());
  const atBottom: TerminalDamageModel[] = [];
  following.subscribe((_state, damage) => atBottom.push(damage));
  atBottom.length = 0;
  assert.deepEqual(following.applyHistory(window), { status: "committed" });
  assert.deepEqual(atBottom, [], "these rows are not on their screen");

  const scrolled = new TerminalClientModel();
  scrolled.applyScreen(hostFrame());
  scrolled.setViewportIntent({ followBottom: false, historyAnchor: 0 });
  const reading: TerminalDamageModel[] = [];
  scrolled.subscribe((_state, damage) => reading.push(damage));
  reading.length = 0;
  assert.deepEqual(scrolled.applyHistory(window), { status: "committed" });
  assert.deepEqual(reading, [{ scope: "full", rows: [] }], "these rows are what they are reading");
});
